import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ItemsSelectProvider } from "./utils/contexts/ItemSelectContext";
import { AuthContextProvider } from "./utils/contexts/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ItemsSelectProvider>
          <AuthContextProvider>
            <div
              style={{ position: "sticky", top: 0, marginTop: 10, zIndex: 10 }}
            >
              <Navbar />
            </div>
            {children}
          </AuthContextProvider>
        </ItemsSelectProvider>
      </body>
    </html>
  );
}
